package com.suning.cn.dto;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table after_goods
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class AfterGoods {
    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_goods.goods_id
     *
     * @mbg.generated
     */
    private String goodsId;

    /**
     * Database Column Remarks:
     *   商品包装说明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_goods.goods_package
     *
     * @mbg.generated
     */
    private String goodsPackage;

    /**
     * Database Column Remarks:
     *   上面售后说明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_goods.after_buy
     *
     * @mbg.generated
     */
    private String afterBuy;

    /**
     * Database Column Remarks:
     *   商品的价格说明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_goods.explaion
     *
     * @mbg.generated
     */
    private String explaion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_goods.goods_id
     *
     * @return the value of after_goods.goods_id
     *
     * @mbg.generated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_goods.goods_id
     *
     * @param goodsId the value for after_goods.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_goods.goods_package
     *
     * @return the value of after_goods.goods_package
     *
     * @mbg.generated
     */
    public String getGoodsPackage() {
        return goodsPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_goods.goods_package
     *
     * @param goodsPackage the value for after_goods.goods_package
     *
     * @mbg.generated
     */
    public void setGoodsPackage(String goodsPackage) {
        this.goodsPackage = goodsPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_goods.after_buy
     *
     * @return the value of after_goods.after_buy
     *
     * @mbg.generated
     */
    public String getAfterBuy() {
        return afterBuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_goods.after_buy
     *
     * @param afterBuy the value for after_goods.after_buy
     *
     * @mbg.generated
     */
    public void setAfterBuy(String afterBuy) {
        this.afterBuy = afterBuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_goods.explaion
     *
     * @return the value of after_goods.explaion
     *
     * @mbg.generated
     */
    public String getExplaion() {
        return explaion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_goods.explaion
     *
     * @param explaion the value for after_goods.explaion
     *
     * @mbg.generated
     */
    public void setExplaion(String explaion) {
        this.explaion = explaion;
    }
}