package com.suning.cn.dto;

import lombok.Data;


@Data
public class AfterGoods {

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_goods.goods_id
     *
     * @mbg.generated
     */
    private String goodsId;

    /**
     * Database Column Remarks:
     *   商品包装说明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_goods.goods_package
     *
     * @mbg.generated
     */
    private String goodsPackage;

    /**
     * Database Column Remarks:
     *   上面售后说明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_goods.after_buy
     *
     * @mbg.generated
     */
    private String afterBuy;

    /**
     * Database Column Remarks:
     *   商品的价格说明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_goods.explaion
     *
     * @mbg.generated
     */
    private String explaion;


}