package com.suning.cn.dto;

import lombok.Data;

import java.util.Date;


@Data
public class Cart {
    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.goods_id
     *
     * @mbg.generated
     */
    private String goodsId;

    /**
     * Database Column Remarks:
     *   商品数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.goods_num
     *
     * @mbg.generated
     */
    private String goodsNum;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   是否删除 （0-删除/1-存在）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.is_del
     *
     * @mbg.generated
     */
    private Integer isDel;


}