package com.suning.cn.dto;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table goods_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class GoodsInfo {
    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.goods_id
     *
     * @mbg.generated
     */
    private String goodsId;

    /**
     * Database Column Remarks:
     *   商品图片的地址列表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.img_list
     *
     * @mbg.generated
     */
    private String imgList;

    /**
     * Database Column Remarks:
     *   商品参数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.datas
     *
     * @mbg.generated
     */
    private String datas;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.goods_id
     *
     * @return the value of goods_info.goods_id
     *
     * @mbg.generated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.goods_id
     *
     * @param goodsId the value for goods_info.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.img_list
     *
     * @return the value of goods_info.img_list
     *
     * @mbg.generated
     */
    public String getImgList() {
        return imgList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.img_list
     *
     * @param imgList the value for goods_info.img_list
     *
     * @mbg.generated
     */
    public void setImgList(String imgList) {
        this.imgList = imgList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.datas
     *
     * @return the value of goods_info.datas
     *
     * @mbg.generated
     */
    public String getDatas() {
        return datas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.datas
     *
     * @param datas the value for goods_info.datas
     *
     * @mbg.generated
     */
    public void setDatas(String datas) {
        this.datas = datas;
    }
}