package com.suning.cn.dto;

import lombok.Data;


@Data
public class GoodsInfo {
    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.goods_id
     *
     * @mbg.generated
     */
    private String goodsId;

    /**
     * Database Column Remarks:
     *   商品图片的地址列表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.img_list
     *
     * @mbg.generated
     */
    private String imgList;

    /**
     * Database Column Remarks:
     *   商品参数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.datas
     *
     * @mbg.generated
     */
    private String datas;


}