package com.suning.cn.dto;

import lombok.Data;

import java.util.Date;

@Data
public class Goods {
    /**
     * Database Column Remarks:
     *   商品id 
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_id
     *
     * @mbg.generated
     */
    private String goodsId;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     * Database Column Remarks:
     *   商品原价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.init_price
     *
     * @mbg.generated
     */
    private Double initPrice;

    /**
     * Database Column Remarks:
     *   商品促销价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.off_price
     *
     * @mbg.generated
     */
    private Double offPrice;

    /**
     * Database Column Remarks:
     *   商品的创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   商品的修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;


}