package com.suning.cn.dto;

import lombok.Data;

import java.util.Date;

@Data
public class GoodsStock {
    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_stock.goods_id
     *
     * @mbg.generated
     */
    private String goodsId;

    /**
     * Database Column Remarks:
     *   商品库存
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_stock.goods_num
     *
     * @mbg.generated
     */
    private String goodsNum;

    /**
     * Database Column Remarks:
     *   商品入库时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_stock.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   商品数量更改的时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_stock.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;


}