package com.suning.cn.dto;

import java.util.ArrayList;
import java.util.List;

public class GoodsInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbg.generated
     */
    public GoodsInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGoodsIdIsNull() {
            addCriterion("goods_id is null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNotNull() {
            addCriterion("goods_id is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdEqualTo(String value) {
            addCriterion("goods_id =", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotEqualTo(String value) {
            addCriterion("goods_id <>", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThan(String value) {
            addCriterion("goods_id >", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThanOrEqualTo(String value) {
            addCriterion("goods_id >=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThan(String value) {
            addCriterion("goods_id <", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThanOrEqualTo(String value) {
            addCriterion("goods_id <=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLike(String value) {
            addCriterion("goods_id like", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotLike(String value) {
            addCriterion("goods_id not like", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIn(List<String> values) {
            addCriterion("goods_id in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotIn(List<String> values) {
            addCriterion("goods_id not in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdBetween(String value1, String value2) {
            addCriterion("goods_id between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotBetween(String value1, String value2) {
            addCriterion("goods_id not between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andImgListIsNull() {
            addCriterion("img_list is null");
            return (Criteria) this;
        }

        public Criteria andImgListIsNotNull() {
            addCriterion("img_list is not null");
            return (Criteria) this;
        }

        public Criteria andImgListEqualTo(String value) {
            addCriterion("img_list =", value, "imgList");
            return (Criteria) this;
        }

        public Criteria andImgListNotEqualTo(String value) {
            addCriterion("img_list <>", value, "imgList");
            return (Criteria) this;
        }

        public Criteria andImgListGreaterThan(String value) {
            addCriterion("img_list >", value, "imgList");
            return (Criteria) this;
        }

        public Criteria andImgListGreaterThanOrEqualTo(String value) {
            addCriterion("img_list >=", value, "imgList");
            return (Criteria) this;
        }

        public Criteria andImgListLessThan(String value) {
            addCriterion("img_list <", value, "imgList");
            return (Criteria) this;
        }

        public Criteria andImgListLessThanOrEqualTo(String value) {
            addCriterion("img_list <=", value, "imgList");
            return (Criteria) this;
        }

        public Criteria andImgListLike(String value) {
            addCriterion("img_list like", value, "imgList");
            return (Criteria) this;
        }

        public Criteria andImgListNotLike(String value) {
            addCriterion("img_list not like", value, "imgList");
            return (Criteria) this;
        }

        public Criteria andImgListIn(List<String> values) {
            addCriterion("img_list in", values, "imgList");
            return (Criteria) this;
        }

        public Criteria andImgListNotIn(List<String> values) {
            addCriterion("img_list not in", values, "imgList");
            return (Criteria) this;
        }

        public Criteria andImgListBetween(String value1, String value2) {
            addCriterion("img_list between", value1, value2, "imgList");
            return (Criteria) this;
        }

        public Criteria andImgListNotBetween(String value1, String value2) {
            addCriterion("img_list not between", value1, value2, "imgList");
            return (Criteria) this;
        }

        public Criteria andDatasIsNull() {
            addCriterion("datas is null");
            return (Criteria) this;
        }

        public Criteria andDatasIsNotNull() {
            addCriterion("datas is not null");
            return (Criteria) this;
        }

        public Criteria andDatasEqualTo(String value) {
            addCriterion("datas =", value, "datas");
            return (Criteria) this;
        }

        public Criteria andDatasNotEqualTo(String value) {
            addCriterion("datas <>", value, "datas");
            return (Criteria) this;
        }

        public Criteria andDatasGreaterThan(String value) {
            addCriterion("datas >", value, "datas");
            return (Criteria) this;
        }

        public Criteria andDatasGreaterThanOrEqualTo(String value) {
            addCriterion("datas >=", value, "datas");
            return (Criteria) this;
        }

        public Criteria andDatasLessThan(String value) {
            addCriterion("datas <", value, "datas");
            return (Criteria) this;
        }

        public Criteria andDatasLessThanOrEqualTo(String value) {
            addCriterion("datas <=", value, "datas");
            return (Criteria) this;
        }

        public Criteria andDatasLike(String value) {
            addCriterion("datas like", value, "datas");
            return (Criteria) this;
        }

        public Criteria andDatasNotLike(String value) {
            addCriterion("datas not like", value, "datas");
            return (Criteria) this;
        }

        public Criteria andDatasIn(List<String> values) {
            addCriterion("datas in", values, "datas");
            return (Criteria) this;
        }

        public Criteria andDatasNotIn(List<String> values) {
            addCriterion("datas not in", values, "datas");
            return (Criteria) this;
        }

        public Criteria andDatasBetween(String value1, String value2) {
            addCriterion("datas between", value1, value2, "datas");
            return (Criteria) this;
        }

        public Criteria andDatasNotBetween(String value1, String value2) {
            addCriterion("datas not between", value1, value2, "datas");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}