package com.suning.cn.dto;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table orders
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Orders {
    /**
     * Database Column Remarks:
     *   订单id编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.goods_id
     *
     * @mbg.generated
     */
    private String goodsId;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   商品数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.count
     *
     * @mbg.generated
     */
    private Integer count;

    /**
     * Database Column Remarks:
     *   总金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.total_cost
     *
     * @mbg.generated
     */
    private Double totalCost;

    /**
     * Database Column Remarks:
     *   优惠金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.off_cost
     *
     * @mbg.generated
     */
    private Double offCost;

    /**
     * Database Column Remarks:
     *   实付金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.real_pay
     *
     * @mbg.generated
     */
    private Double realPay;

    /**
     * Database Column Remarks:
     *   订单状态（0-待支付/1-待收货/2-已完成）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.is_del
     *
     * @mbg.generated
     */
    private Integer isDel;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_id
     *
     * @return the value of orders.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_id
     *
     * @param orderId the value for orders.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.goods_id
     *
     * @return the value of orders.goods_id
     *
     * @mbg.generated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.goods_id
     *
     * @param goodsId the value for orders.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_id
     *
     * @return the value of orders.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_id
     *
     * @param userId the value for orders.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.count
     *
     * @return the value of orders.count
     *
     * @mbg.generated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.count
     *
     * @param count the value for orders.count
     *
     * @mbg.generated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.total_cost
     *
     * @return the value of orders.total_cost
     *
     * @mbg.generated
     */
    public Double getTotalCost() {
        return totalCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.total_cost
     *
     * @param totalCost the value for orders.total_cost
     *
     * @mbg.generated
     */
    public void setTotalCost(Double totalCost) {
        this.totalCost = totalCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.off_cost
     *
     * @return the value of orders.off_cost
     *
     * @mbg.generated
     */
    public Double getOffCost() {
        return offCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.off_cost
     *
     * @param offCost the value for orders.off_cost
     *
     * @mbg.generated
     */
    public void setOffCost(Double offCost) {
        this.offCost = offCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.real_pay
     *
     * @return the value of orders.real_pay
     *
     * @mbg.generated
     */
    public Double getRealPay() {
        return realPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.real_pay
     *
     * @param realPay the value for orders.real_pay
     *
     * @mbg.generated
     */
    public void setRealPay(Double realPay) {
        this.realPay = realPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.is_del
     *
     * @return the value of orders.is_del
     *
     * @mbg.generated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.is_del
     *
     * @param isDel the value for orders.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.create_time
     *
     * @return the value of orders.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.create_time
     *
     * @param createTime the value for orders.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.modify_time
     *
     * @return the value of orders.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.modify_time
     *
     * @param modifyTime the value for orders.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}