package com.suning.cn.dto;

import lombok.Data;

@Data
public class RelationalShop {
    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relational_shop.goods_id
     *
     * @mbg.generated
     */
    private String goodsId;

    /**
     * Database Column Remarks:
     *   店铺id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relational_shop.shop_id
     *
     * @mbg.generated
     */
    private String shopId;


}