package com.suning.cn.dto;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table reviews
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Reviews {
    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.goods_id
     *
     * @mbg.generated
     */
    private String goodsId;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   评价内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * Database Column Remarks:
     *   评分 (总五星：1/2/3/4/5)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     * Database Column Remarks:
     *   评价图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.images
     *
     * @mbg.generated
     */
    private String images;

    /**
     * Database Column Remarks:
     *   点赞
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.like
     *
     * @mbg.generated
     */
    private Integer like;

    /**
     * Database Column Remarks:
     *   用户的评价时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews.goods_id
     *
     * @return the value of reviews.goods_id
     *
     * @mbg.generated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews.goods_id
     *
     * @param goodsId the value for reviews.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews.user_id
     *
     * @return the value of reviews.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews.user_id
     *
     * @param userId the value for reviews.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews.content
     *
     * @return the value of reviews.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews.content
     *
     * @param content the value for reviews.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews.score
     *
     * @return the value of reviews.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews.score
     *
     * @param score the value for reviews.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews.images
     *
     * @return the value of reviews.images
     *
     * @mbg.generated
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews.images
     *
     * @param images the value for reviews.images
     *
     * @mbg.generated
     */
    public void setImages(String images) {
        this.images = images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews.like
     *
     * @return the value of reviews.like
     *
     * @mbg.generated
     */
    public Integer getLike() {
        return like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews.like
     *
     * @param like the value for reviews.like
     *
     * @mbg.generated
     */
    public void setLike(Integer like) {
        this.like = like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews.create_time
     *
     * @return the value of reviews.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews.create_time
     *
     * @param createTime the value for reviews.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}