package com.suning.cn.dto;

import lombok.Data;

import java.util.Date;

@Data
public class Reviews {
    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.goods_id
     *
     * @mbg.generated
     */
    private String goodsId;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   评价内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * Database Column Remarks:
     *   评分 (总五星：1/2/3/4/5)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     * Database Column Remarks:
     *   评价图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.images
     *
     * @mbg.generated
     */
    private String images;

    /**
     * Database Column Remarks:
     *   用户的评价时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.create_time
     *
     * @mbg.generated
     */
    private Date createTime;


}