package com.suning.cn.dto;

import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table shipping_address
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class ShippingAddress {
    /**
     * Database Column Remarks:
     *   收件人的用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipping_address.user_id
     *
     * @mbg.generated
     */
    private String userId;


    /**
     * Database Column Remarks:
     *   地址id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipping_address.address_id
     *
     * @mbg.generated
     */
    private String addressId;

    /**
     * Database Column Remarks:
     *   收件人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipping_address.reciver
     *
     * @mbg.generated
     */
    private String reciver;

    /**
     * Database Column Remarks:
     *   收件人手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipping_address.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   收货地区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipping_address.region
     *
     * @mbg.generated
     */
    private String region;

    /**
     * Database Column Remarks:
     *   收货的详细地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipping_address.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   地址的邮编（可不填）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipping_address.mail_code
     *
     * @mbg.generated
     */
    private String mailCode;

    /**
     * Database Column Remarks:
     *   选择默认地址（0-非默认、1-默认）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipping_address.is_default
     *
     * @mbg.generated
     */
    private Integer isDefault;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipping_address.user_id
     *
     * @return the value of shipping_address.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipping_address.user_id
     *
     * @param userId the value for shipping_address.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipping_address.address_id
     *
     * @return the value of shipping_address.address_id
     *
     * @mbg.generated
     * @param address_id
     */
    public String getAddressId(String address_id) {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipping_address.address_id
     *
     * @param addressId the value for shipping_address.address_id
     *
     * @mbg.generated
     */
    public void setAddressId(String addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipping_address.reciver
     *
     * @return the value of shipping_address.reciver
     *
     * @mbg.generated
     */
    public String getReciver() {
        return reciver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipping_address.reciver
     *
     * @param reciver the value for shipping_address.reciver
     *
     * @mbg.generated
     */
    public void setReciver(String reciver) {
        this.reciver = reciver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipping_address.phone
     *
     * @return the value of shipping_address.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipping_address.phone
     *
     * @param phone the value for shipping_address.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipping_address.region
     *
     * @return the value of shipping_address.region
     *
     * @mbg.generated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipping_address.region
     *
     * @param region the value for shipping_address.region
     *
     * @mbg.generated
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipping_address.address
     *
     * @return the value of shipping_address.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipping_address.address
     *
     * @param address the value for shipping_address.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipping_address.mail_code
     *
     * @return the value of shipping_address.mail_code
     *
     * @mbg.generated
     */
    public String getMailCode() {
        return mailCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipping_address.mail_code
     *
     * @param mailCode the value for shipping_address.mail_code
     *
     * @mbg.generated
     */
    public void setMailCode(String mailCode) {
        this.mailCode = mailCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipping_address.is_default
     *
     * @return the value of shipping_address.is_default
     *
     * @mbg.generated
     */
    public Integer getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipping_address.is_default
     *
     * @param isDefault the value for shipping_address.is_default
     *
     * @mbg.generated
     */
    public void setIsDefault(Integer isDefault) {
        this.isDefault = isDefault;
    }
}