package com.suning.cn.dto;

import lombok.Data;

@Data
public class ShippingAddress {
    /**
     * Database Column Remarks:
     *   收件人的用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipping_address.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   收件人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipping_address.reciver
     *
     * @mbg.generated
     */
    private String reciver;

    /**
     * Database Column Remarks:
     *   收件人手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipping_address.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   收货地区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipping_address.region
     *
     * @mbg.generated
     */
    private String region;

    /**
     * Database Column Remarks:
     *   收货的详细地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipping_address.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   地址的邮编（可不填）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipping_address.mail_code
     *
     * @mbg.generated
     */
    private String mailCode;

    /**
     * Database Column Remarks:
     *   选择默认地址（0-非默认、1-默认）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipping_address.is_default
     *
     * @mbg.generated
     */
    private Integer isDefault;


}