package com.suning.cn.dto;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table shops
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Shops {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.shops_id
     *
     * @mbg.generated
     */
    private String shopsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.shops_name
     *
     * @mbg.generated
     */
    private String shopsName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.shops_id
     *
     * @return the value of shops.shops_id
     *
     * @mbg.generated
     */
    public String getShopsId() {
        return shopsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.shops_id
     *
     * @param shopsId the value for shops.shops_id
     *
     * @mbg.generated
     */
    public void setShopsId(String shopsId) {
        this.shopsId = shopsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.shops_name
     *
     * @return the value of shops.shops_name
     *
     * @mbg.generated
     */
    public String getShopsName() {
        return shopsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.shops_name
     *
     * @param shopsName the value for shops.shops_name
     *
     * @mbg.generated
     */
    public void setShopsName(String shopsName) {
        this.shopsName = shopsName;
    }
}