package com.suning.cn.dto;

import lombok.Data;

@Data
public class Types {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column types.type_id
     *
     * @mbg.generated
     */
    private String typeId;

    /**
     * Database Column Remarks:
     *   类型名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column types.type_name
     *
     * @mbg.generated
     */
    private String typeName;

    /**
     * Database Column Remarks:
     *   类型地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column types.type_url
     *
     * @mbg.generated
     */
    private String typeUrl;


}