package com.suning.cn.dto;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table types
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Types {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column types.type_id
     *
     * @mbg.generated
     */
    private String typeId;

    /**
     * Database Column Remarks:
     *   类型名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column types.type_name
     *
     * @mbg.generated
     */
    private String typeName;

    /**
     * Database Column Remarks:
     *   类型地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column types.type_url
     *
     * @mbg.generated
     */
    private String typeUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column types.type_id
     *
     * @return the value of types.type_id
     *
     * @mbg.generated
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column types.type_id
     *
     * @param typeId the value for types.type_id
     *
     * @mbg.generated
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column types.type_name
     *
     * @return the value of types.type_name
     *
     * @mbg.generated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column types.type_name
     *
     * @param typeName the value for types.type_name
     *
     * @mbg.generated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column types.type_url
     *
     * @return the value of types.type_url
     *
     * @mbg.generated
     */
    public String getTypeUrl() {
        return typeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column types.type_url
     *
     * @param typeUrl the value for types.type_url
     *
     * @mbg.generated
     */
    public void setTypeUrl(String typeUrl) {
        this.typeUrl = typeUrl;
    }
}