package com.suning.cn.mapper;

import com.suning.cn.dto.AfterGoods;
import com.suning.cn.dto.AfterGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AfterGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_goods
     *
     * @mbg.generated
     */
    long countByExample(AfterGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_goods
     *
     * @mbg.generated
     */
    int deleteByExample(AfterGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_goods
     *
     * @mbg.generated
     */
    int insert(AfterGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_goods
     *
     * @mbg.generated
     */
    int insertSelective(AfterGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_goods
     *
     * @mbg.generated
     */
    List<AfterGoods> selectByExample(AfterGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AfterGoods record, @Param("example") AfterGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AfterGoods record, @Param("example") AfterGoodsExample example);
}