package com.suning.cn.mapper;

import com.suning.cn.dto.GoodsStock;
import com.suning.cn.dto.GoodsStockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     */
    long countByExample(GoodsStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     */
    int deleteByExample(GoodsStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     */
    int insert(GoodsStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     */
    int insertSelective(GoodsStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     */
    List<GoodsStock> selectByExample(GoodsStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     */
    GoodsStock selectByPrimaryKey(String goodsId);

    int selectNumByPrimaryKey(String goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GoodsStock record, @Param("example") GoodsStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GoodsStock record, @Param("example") GoodsStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GoodsStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodsStock record);
}