package com.suning.cn.mapper;

import com.suning.cn.dto.ImgExchange;
import com.suning.cn.dto.ImgExchangeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImgExchangeMapper {

    String selectThumbImgBygoodsIdAndMain(@Param("goodsId") String goodsId, @Param("isMain")String isMain);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_exchange
     *
     * @mbg.generated
     */
    long countByExample(ImgExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_exchange
     *
     * @mbg.generated
     */
    int deleteByExample(ImgExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_exchange
     *
     * @mbg.generated
     */
    int insert(ImgExchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_exchange
     *
     * @mbg.generated
     */
    int insertSelective(ImgExchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_exchange
     *
     * @mbg.generated
     */
    List<ImgExchange> selectByExample(ImgExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_exchange
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ImgExchange record, @Param("example") ImgExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_exchange
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ImgExchange record, @Param("example") ImgExchangeExample example);
}