package com.suning.cn.mapper;

import com.suning.cn.dto.Reviews;
import com.suning.cn.dto.ReviewsExample;

import java.util.List;

import com.suning.cn.utils.ReturnResult;
import org.apache.ibatis.annotations.Param;

public interface ReviewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated
     */
    long countByExample(ReviewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated
     */
    int deleteByExample(ReviewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated
     */
    int insert(Reviews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated
     */
    int insertSelective(Reviews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated
     */
    List<Reviews> selectByExample(ReviewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Reviews record, @Param("example") ReviewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Reviews record, @Param("example") ReviewsExample example);

    List<Reviews> selectByGoodsId(@Param("goodsId") String goodsId, @Param("limit") Integer limit);

    long countByGoodsId(String goodsId);

    int insertReviewInfo(Reviews reviews);
}